#!/bin/bash
DOCKER_USER_NAME=uvclab
DOCKER_IMAGE_NAME=flexing-mcs-server
DOCKER_IMAGE_TAG=3.1.0

docker build -t $DOCKER_USER_NAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

# docker build --no-cache -t $DOCKER_USER_NAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .